/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

/**
 * Not Found
 */
export type NotificationsControllerGetActivityStatsNotificationsStatsResponseBodyData =
  {
    data?: components.ErrorDto | undefined;
  };

/**
 * Not Found
 */
export class NotificationsControllerGetActivityStatsNotificationsStatsResponseBody
  extends Error
{
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBodyData;

  constructor(
    err:
      NotificationsControllerGetActivityStatsNotificationsStatsResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name =
      "NotificationsControllerGetActivityStatsNotificationsStatsResponseBody";
  }
}

/**
 * Bad Request
 */
export type NotificationsControllerGetActivityStatsResponseBodyData = {
  data?: components.ErrorDto | undefined;
};

/**
 * Bad Request
 */
export class NotificationsControllerGetActivityStatsResponseBody extends Error {
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotificationsControllerGetActivityStatsResponseBodyData;

  constructor(err: NotificationsControllerGetActivityStatsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name = "NotificationsControllerGetActivityStatsResponseBody";
  }
}

/** @internal */
export const NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$inboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new NotificationsControllerGetActivityStatsNotificationsStatsResponseBody(
        v,
      );
    });

/** @internal */
export type NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$Outbound =
  {
    data?: components.ErrorDto$Outbound | undefined;
  };

/** @internal */
export const NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$outboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$Outbound,
    z.ZodTypeDef,
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody
  > = z.instanceof(
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$ {
  /** @deprecated use `NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$inboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$outboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$Outbound` instead. */
  export type Outbound =
    NotificationsControllerGetActivityStatsNotificationsStatsResponseBody$Outbound;
}

/** @internal */
export const NotificationsControllerGetActivityStatsResponseBody$inboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityStatsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new NotificationsControllerGetActivityStatsResponseBody(v);
    });

/** @internal */
export type NotificationsControllerGetActivityStatsResponseBody$Outbound = {
  data?: components.ErrorDto$Outbound | undefined;
};

/** @internal */
export const NotificationsControllerGetActivityStatsResponseBody$outboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityStatsResponseBody$Outbound,
    z.ZodTypeDef,
    NotificationsControllerGetActivityStatsResponseBody
  > = z.instanceof(NotificationsControllerGetActivityStatsResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationsControllerGetActivityStatsResponseBody$ {
  /** @deprecated use `NotificationsControllerGetActivityStatsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    NotificationsControllerGetActivityStatsResponseBody$inboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityStatsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    NotificationsControllerGetActivityStatsResponseBody$outboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityStatsResponseBody$Outbound` instead. */
  export type Outbound =
    NotificationsControllerGetActivityStatsResponseBody$Outbound;
}
