/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

/**
 * Not Found
 */
export type NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBodyData =
  {
    data?: components.ErrorDto | undefined;
  };

/**
 * Not Found
 */
export class NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody
  extends Error
{
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBodyData;

  constructor(
    err:
      NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name =
      "NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody";
  }
}

/**
 * Bad Request
 */
export type NotificationsControllerGetActivityGraphStatsResponseBodyData = {
  data?: components.ErrorDto | undefined;
};

/**
 * Bad Request
 */
export class NotificationsControllerGetActivityGraphStatsResponseBody
  extends Error
{
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotificationsControllerGetActivityGraphStatsResponseBodyData;

  constructor(
    err: NotificationsControllerGetActivityGraphStatsResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name = "NotificationsControllerGetActivityGraphStatsResponseBody";
  }
}

/** @internal */
export const NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$inboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody(
        v,
      );
    });

/** @internal */
export type NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$Outbound =
  {
    data?: components.ErrorDto$Outbound | undefined;
  };

/** @internal */
export const NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$outboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$Outbound,
    z.ZodTypeDef,
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody
  > = z.instanceof(
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$ {
  /** @deprecated use `NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$inboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$outboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$Outbound` instead. */
  export type Outbound =
    NotificationsControllerGetActivityGraphStatsNotificationsStatsResponseBody$Outbound;
}

/** @internal */
export const NotificationsControllerGetActivityGraphStatsResponseBody$inboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityGraphStatsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new NotificationsControllerGetActivityGraphStatsResponseBody(v);
    });

/** @internal */
export type NotificationsControllerGetActivityGraphStatsResponseBody$Outbound =
  {
    data?: components.ErrorDto$Outbound | undefined;
  };

/** @internal */
export const NotificationsControllerGetActivityGraphStatsResponseBody$outboundSchema:
  z.ZodType<
    NotificationsControllerGetActivityGraphStatsResponseBody$Outbound,
    z.ZodTypeDef,
    NotificationsControllerGetActivityGraphStatsResponseBody
  > = z.instanceof(NotificationsControllerGetActivityGraphStatsResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationsControllerGetActivityGraphStatsResponseBody$ {
  /** @deprecated use `NotificationsControllerGetActivityGraphStatsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    NotificationsControllerGetActivityGraphStatsResponseBody$inboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityGraphStatsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    NotificationsControllerGetActivityGraphStatsResponseBody$outboundSchema;
  /** @deprecated use `NotificationsControllerGetActivityGraphStatsResponseBody$Outbound` instead. */
  export type Outbound =
    NotificationsControllerGetActivityGraphStatsResponseBody$Outbound;
}
