/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

/**
 * Not Found
 */
export type SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBodyData =
  {
    data?: components.ErrorDto | undefined;
  };

/**
 * Not Found
 */
export class SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody
  extends Error
{
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$:
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBodyData;

  constructor(
    err:
      SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name =
      "SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody";
  }
}

/**
 * Bad Request
 */
export type SubscribersControllerModifySubscriberChannelResponseBodyData = {
  data?: components.ErrorDto | undefined;
};

/**
 * Bad Request
 */
export class SubscribersControllerModifySubscriberChannelResponseBody
  extends Error
{
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$: SubscribersControllerModifySubscriberChannelResponseBodyData;

  constructor(
    err: SubscribersControllerModifySubscriberChannelResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name = "SubscribersControllerModifySubscriberChannelResponseBody";
  }
}

/** @internal */
export const SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$inboundSchema:
  z.ZodType<
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody(
        v,
      );
    });

/** @internal */
export type SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$Outbound =
  {
    data?: components.ErrorDto$Outbound | undefined;
  };

/** @internal */
export const SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$outboundSchema:
  z.ZodType<
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$Outbound,
    z.ZodTypeDef,
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody
  > = z.instanceof(
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$ {
  /** @deprecated use `SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$inboundSchema;
  /** @deprecated use `SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$outboundSchema;
  /** @deprecated use `SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$Outbound` instead. */
  export type Outbound =
    SubscribersControllerModifySubscriberChannelSubscribersCredentialsResponseBody$Outbound;
}

/** @internal */
export const SubscribersControllerModifySubscriberChannelResponseBody$inboundSchema:
  z.ZodType<
    SubscribersControllerModifySubscriberChannelResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new SubscribersControllerModifySubscriberChannelResponseBody(v);
    });

/** @internal */
export type SubscribersControllerModifySubscriberChannelResponseBody$Outbound =
  {
    data?: components.ErrorDto$Outbound | undefined;
  };

/** @internal */
export const SubscribersControllerModifySubscriberChannelResponseBody$outboundSchema:
  z.ZodType<
    SubscribersControllerModifySubscriberChannelResponseBody$Outbound,
    z.ZodTypeDef,
    SubscribersControllerModifySubscriberChannelResponseBody
  > = z.instanceof(SubscribersControllerModifySubscriberChannelResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscribersControllerModifySubscriberChannelResponseBody$ {
  /** @deprecated use `SubscribersControllerModifySubscriberChannelResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    SubscribersControllerModifySubscriberChannelResponseBody$inboundSchema;
  /** @deprecated use `SubscribersControllerModifySubscriberChannelResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    SubscribersControllerModifySubscriberChannelResponseBody$outboundSchema;
  /** @deprecated use `SubscribersControllerModifySubscriberChannelResponseBody$Outbound` instead. */
  export type Outbound =
    SubscribersControllerModifySubscriberChannelResponseBody$Outbound;
}
