/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

/**
 * Not Found
 */
export type TopicsControllerRemoveSubscribersTopicsSubscribersResponseBodyData =
  {
    data?: components.ErrorDto | undefined;
  };

/**
 * Not Found
 */
export class TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody
  extends Error
{
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$: TopicsControllerRemoveSubscribersTopicsSubscribersResponseBodyData;

  constructor(
    err: TopicsControllerRemoveSubscribersTopicsSubscribersResponseBodyData,
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name =
      "TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody";
  }
}

/**
 * Bad Request
 */
export type TopicsControllerRemoveSubscribersResponseBodyData = {
  data?: components.ErrorDto | undefined;
};

/**
 * Bad Request
 */
export class TopicsControllerRemoveSubscribersResponseBody extends Error {
  data?: components.ErrorDto | undefined;

  /** The original data that was passed to this error instance. */
  data$: TopicsControllerRemoveSubscribersResponseBodyData;

  constructor(err: TopicsControllerRemoveSubscribersResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.data != null) this.data = err.data;

    this.name = "TopicsControllerRemoveSubscribersResponseBody";
  }
}

/** @internal */
export const TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$inboundSchema:
  z.ZodType<
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody(
        v,
      );
    });

/** @internal */
export type TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$Outbound =
  {
    data?: components.ErrorDto$Outbound | undefined;
  };

/** @internal */
export const TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$outboundSchema:
  z.ZodType<
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$Outbound,
    z.ZodTypeDef,
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody
  > = z.instanceof(
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$ {
  /** @deprecated use `TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$inboundSchema;
  /** @deprecated use `TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$outboundSchema;
  /** @deprecated use `TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$Outbound` instead. */
  export type Outbound =
    TopicsControllerRemoveSubscribersTopicsSubscribersResponseBody$Outbound;
}

/** @internal */
export const TopicsControllerRemoveSubscribersResponseBody$inboundSchema:
  z.ZodType<
    TopicsControllerRemoveSubscribersResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: components.ErrorDto$inboundSchema.optional(),
  })
    .transform((v) => {
      return new TopicsControllerRemoveSubscribersResponseBody(v);
    });

/** @internal */
export type TopicsControllerRemoveSubscribersResponseBody$Outbound = {
  data?: components.ErrorDto$Outbound | undefined;
};

/** @internal */
export const TopicsControllerRemoveSubscribersResponseBody$outboundSchema:
  z.ZodType<
    TopicsControllerRemoveSubscribersResponseBody$Outbound,
    z.ZodTypeDef,
    TopicsControllerRemoveSubscribersResponseBody
  > = z.instanceof(TopicsControllerRemoveSubscribersResponseBody)
    .transform(v => v.data$)
    .pipe(z.object({
      data: components.ErrorDto$outboundSchema.optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicsControllerRemoveSubscribersResponseBody$ {
  /** @deprecated use `TopicsControllerRemoveSubscribersResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    TopicsControllerRemoveSubscribersResponseBody$inboundSchema;
  /** @deprecated use `TopicsControllerRemoveSubscribersResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    TopicsControllerRemoveSubscribersResponseBody$outboundSchema;
  /** @deprecated use `TopicsControllerRemoveSubscribersResponseBody$Outbound` instead. */
  export type Outbound = TopicsControllerRemoveSubscribersResponseBody$Outbound;
}
