/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { inboundWebhooksControllerHandleWebhook } from "../../funcs/inboundWebhooksControllerHandleWebhook.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  environmentId: z.string(),
  integrationId: z.string(),
  idempotencyKey: z.string().optional(),
};

export const tool$inboundWebhooksControllerHandleWebhook: ToolDefinition<
  typeof args
> = {
  name: "inbound-webhooks-controller-handle-webhook",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await inboundWebhooksControllerHandleWebhook(
      client,
      args.environmentId,
      args.integrationId,
      args.idempotencyKey,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
