/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { integrationsList } from "../../funcs/integrationsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  idempotencyKey: z.string().optional(),
};

export const tool$integrationsList: ToolDefinition<typeof args> = {
  name: "integrations_list",
  description: `Get integrations

Return all the integrations the user has created for that organization. Review v.0.17.0 changelog for a breaking change`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsList(
      client,
      args.idempotencyKey,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
