/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { notificationsStatsRetrieve } from "../../funcs/notificationsStatsRetrieve.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  idempotencyKey: z.string().optional(),
};

export const tool$notificationsStatsRetrieve: ToolDefinition<typeof args> = {
  name: "notifications-stats_retrieve",
  description: `Get notification statistics`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationsStatsRetrieve(
      client,
      args.idempotencyKey,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
