/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { subscribersPreferencesList } from "../../funcs/subscribersPreferencesList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  subscriberId: z.string(),
  idempotencyKey: z.string().optional(),
};

export const tool$subscribersPreferencesList: ToolDefinition<typeof args> = {
  name: "subscribers-preferences-list",
  description: `Retrieve subscriber preferences

Retrieve subscriber channel preferences by its unique key identifier **subscriberId**. 
    This API returns all five channels preferences for all workflows and global preferences.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscribersPreferencesList(
      client,
      args.subscriberId,
      args.idempotencyKey,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
