/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscribersNotificationsFeed } from "../../funcs/subscribersNotificationsFeed.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.SubscribersV1ControllerGetNotificationsFeedRequest$inboundSchema,
};

export const tool$subscribersNotificationsFeed: ToolDefinition<typeof args> = {
  name: "subscribers-notifications_feed",
  description: `Get in-app notification feed for a particular subscriber`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscribersNotificationsFeed(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
