/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { topicsUpdate } from "../../funcs/topicsUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  updateTopicRequestDto: components.UpdateTopicRequestDto$inboundSchema,
  topicKey: z.string(),
  idempotencyKey: z.string().optional(),
};

export const tool$topicsUpdate: ToolDefinition<typeof args> = {
  name: "topics-update",
  description: `Update a topic

Update a topic name by its unique key identifier **topicKey**`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await topicsUpdate(
      client,
      args.updateTopicRequestDto,
      args.topicKey,
      args.idempotencyKey,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
