/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { topicsSubscriptionsCreate } from "../../funcs/topicsSubscriptionsCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  createTopicSubscriptionsRequestDto:
    components.CreateTopicSubscriptionsRequestDto$inboundSchema,
  topicKey: z.string(),
  idempotencyKey: z.string().optional(),
};

export const tool$topicsSubscriptionsCreate: ToolDefinition<typeof args> = {
  name: "topics-subscriptions-create",
  description:
    `Create topic subscriptions, if the topic does not exist, it will be created.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await topicsSubscriptionsCreate(
      client,
      args.createTopicSubscriptionsRequestDto,
      args.topicKey,
      args.idempotencyKey,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
