/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsList } from "../../funcs/workflowsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.WorkflowControllerSearchWorkflowsRequest$inboundSchema,
};

export const tool$workflowsList: ToolDefinition<typeof args> = {
  name: "workflows-list",
  description: `List all workflows

Retrieves a list of workflows with optional filtering and pagination`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workflowsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
