/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

let value: StepResponseDto = {
  controls: {},
  providerOverrides: {
    "slack": {
      "text": "{{"{{"}}payload.title}}",
      "blocks": [
        {
          "type": "divider",
        },
      ],
    },
    "whatsapp-business": {
      "type": "text",
      "text": {
        "body": "{{"{{"}}payload.title}}",
      },
    },
    "pagerduty": {
      "severity": "warning",
      "source": "novu",
      "summary": "{{"{{"}}payload.title}}",
    },
  },
  variables: {
    "key": "<value>",
    "key1": "<value>",
  },
  stepId: "<id>",
  id: "<id>",
  name: "<value>",
  slug: "<value>",
  type: "<value>",
  origin: "external",
  workflowId: "<id>",
  workflowDatabaseId: "<id>",
};