/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminTestingControllerIdempotency } from "../funcs/adminTestingControllerIdempotency.js";
import { adminTestingControllerIdempotencyGet } from "../funcs/adminTestingControllerIdempotencyGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Admin extends ClientSDK {
  async testingControllerIdempotency(
    idempotencyBodyDto: components.IdempotencyBodyDto,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.TestingControllerIdempotencyResponse> {
    return unwrapAsync(adminTestingControllerIdempotency(
      this,
      idempotencyBodyDto,
      idempotencyKey,
      options,
    ));
  }

  async testingControllerIdempotencyGet(
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.TestingControllerIdempotencyGetResponse> {
    return unwrapAsync(adminTestingControllerIdempotencyGet(
      this,
      idempotencyKey,
      options,
    ));
  }
}
