/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import { encodeJSON as encodeJSON$, encodeSimple as encodeSimple$ } from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import { SecurityInput } from "../lib/security";
import * as components from "../models/components";
import * as operations from "../models/operations";
import { Changes } from "./changes";
import { Environments } from "./environments";
import { Events } from "./events";
import { ExecutionDetails } from "./executiondetails";
import { Feeds } from "./feeds";
import { Integrations } from "./integrations";
import { Layouts } from "./layouts";
import { Messages } from "./messages";
import { Notifications } from "./notifications";
import { Organizations } from "./organizations";
import { Subscribers } from "./subscribers";
import { Tenants } from "./tenants";
import { Topics } from "./topics";
import { WorkflowGroups } from "./workflowgroups";
import { Workflows } from "./workflows";

export class Novu extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    private _organizations?: Organizations;
    get organizations(): Organizations {
        return (this._organizations ??= new Organizations(this.options$));
    }

    private _environments?: Environments;
    get environments(): Environments {
        return (this._environments ??= new Environments(this.options$));
    }

    private _executionDetails?: ExecutionDetails;
    get executionDetails(): ExecutionDetails {
        return (this._executionDetails ??= new ExecutionDetails(this.options$));
    }

    private _workflows?: Workflows;
    get workflows(): Workflows {
        return (this._workflows ??= new Workflows(this.options$));
    }

    private _events?: Events;
    get events(): Events {
        return (this._events ??= new Events(this.options$));
    }

    private _notifications?: Notifications;
    get notifications(): Notifications {
        return (this._notifications ??= new Notifications(this.options$));
    }

    private _workflowGroups?: WorkflowGroups;
    get workflowGroups(): WorkflowGroups {
        return (this._workflowGroups ??= new WorkflowGroups(this.options$));
    }

    private _integrations?: Integrations;
    get integrations(): Integrations {
        return (this._integrations ??= new Integrations(this.options$));
    }

    private _changes?: Changes;
    get changes(): Changes {
        return (this._changes ??= new Changes(this.options$));
    }

    private _subscribers?: Subscribers;
    get subscribers(): Subscribers {
        return (this._subscribers ??= new Subscribers(this.options$));
    }

    private _feeds?: Feeds;
    get feeds(): Feeds {
        return (this._feeds ??= new Feeds(this.options$));
    }

    private _layouts?: Layouts;
    get layouts(): Layouts {
        return (this._layouts ??= new Layouts(this.options$));
    }

    private _messages?: Messages;
    get messages(): Messages {
        return (this._messages ??= new Messages(this.options$));
    }

    private _topics?: Topics;
    get topics(): Topics {
        return (this._topics ??= new Topics(this.options$));
    }

    private _tenants?: Tenants;
    get tenants(): Tenants {
        return (this._tenants ??= new Tenants(this.options$));
    }

    /**
     * Create workflow
     *
     * @remarks
     * Workflow was previously named notification template
     */
    async create(
        request: components.CreateWorkflowRequestDto,
        security: operations.CreateSecurity,
        options?: RequestOptions
    ): Promise<components.WorkflowResponse> {
        const input$ = request;
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => components.CreateWorkflowRequestDto$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/workflows")();

        const query$ = "";

        const security$: SecurityInput[][] = [
            [
                {
                    fieldName: "Authorization",
                    type: "http:bearer",
                    value: security?.bearer,
                },
            ],
            [
                {
                    fieldName: "Authorization",
                    type: "apiKey:header",
                    value: security?.apiKey,
                },
            ],
        ];
        const securitySettings$ = this.resolveSecurity(...security$);
        const context = { operationID: "create", oAuth2Scopes: [], securitySource: security$ };

        const doOptions = { context, errorCodes: ["409", "429", "4XX", "503", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const [result$] = await this.matcher<components.WorkflowResponse>()
            .json(201, components.WorkflowResponse$)
            .fail([409, 429, "4XX", 503, "5XX"])
            .match(response);

        return result$;
    }

    /**
     * Get workflow
     *
     * @remarks
     * Workflow was previously named notification template
     */
    async retrieve(
        security: operations.GetWorkflowByIdSecurity,
        workflowId: string,
        options?: RequestOptions
    ): Promise<components.WorkflowResponse> {
        const input$: operations.GetWorkflowByIdRequest = {
            workflowId: workflowId,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetWorkflowByIdRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            workflowId: encodeSimple$("workflowId", payload$.workflowId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/workflows/{workflowId}")(pathParams$);

        const query$ = "";

        const security$: SecurityInput[][] = [
            [
                {
                    fieldName: "Authorization",
                    type: "http:bearer",
                    value: security?.bearer,
                },
            ],
            [
                {
                    fieldName: "Authorization",
                    type: "apiKey:header",
                    value: security?.apiKey,
                },
            ],
        ];
        const securitySettings$ = this.resolveSecurity(...security$);
        const context = {
            operationID: "getWorkflowById",
            oAuth2Scopes: [],
            securitySource: security$,
        };

        const doOptions = { context, errorCodes: ["409", "429", "4XX", "503", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const [result$] = await this.matcher<components.WorkflowResponse>()
            .json(200, components.WorkflowResponse$)
            .fail([409, 429, "4XX", 503, "5XX"])
            .match(response);

        return result$;
    }

    /**
     * Update workflow status
     *
     * @remarks
     * Workflow was previously named notification template
     */
    async changeActiveStatus(
        security: operations.ChangeActiveStatusSecurity,
        workflowId: string,
        changeWorkflowStatusRequestDto: components.ChangeWorkflowStatusRequestDto,
        options?: RequestOptions
    ): Promise<components.WorkflowResponse> {
        const input$: operations.ChangeActiveStatusRequest = {
            workflowId: workflowId,
            changeWorkflowStatusRequestDto: changeWorkflowStatusRequestDto,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ChangeActiveStatusRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.ChangeWorkflowStatusRequestDto, {
            explode: true,
        });

        const pathParams$ = {
            workflowId: encodeSimple$("workflowId", payload$.workflowId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/workflows/{workflowId}/status")(pathParams$);

        const query$ = "";

        const security$: SecurityInput[][] = [
            [
                {
                    fieldName: "Authorization",
                    type: "http:bearer",
                    value: security?.bearer,
                },
            ],
            [
                {
                    fieldName: "Authorization",
                    type: "apiKey:header",
                    value: security?.apiKey,
                },
            ],
        ];
        const securitySettings$ = this.resolveSecurity(...security$);
        const context = {
            operationID: "changeActiveStatus",
            oAuth2Scopes: [],
            securitySource: security$,
        };

        const doOptions = { context, errorCodes: ["409", "429", "4XX", "503", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "PUT",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const [result$] = await this.matcher<components.WorkflowResponse>()
            .json(200, components.WorkflowResponse$)
            .fail([409, 429, "4XX", 503, "5XX"])
            .match(response);

        return result$;
    }
}
