workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    json-development:
        inputs:
            - location: http://127.0.0.1:3000/openapi.sdk.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: sources/json-development.json
        registry:
            location: registry.speakeasyapi.dev/novu/novu/json-development
targets:
    my-first-target:
        target: typescript
        source: json-development
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: sources/code-samples.yaml
            registry:
                location: registry.speakeasyapi.dev/novu/novu/code-samples-typescript
