workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    json-development:
        inputs:
            - location: http://api.novu.co/openapi.sdk.json
            # - location: ./sources/openapi.sdk.json
        overlays:
            - location: ./sources/cleanup-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/novu/novu/json-development
        output: sources/json-development.json
targets:
    my-first-target:
        target: typescript
        source: json-development
        codeSamples:
            output: sources/code-samples.json
            registry:
                location: registry.speakeasyapi.dev/novu/novu/code-samples-typescript
        publish:
            npm:
                token: $npm_token
