/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ChangesControllerApplyDiffRequest = {
    changeId: string;
};

/** @internal */
export namespace ChangesControllerApplyDiffRequest$ {
    export const inboundSchema: z.ZodType<
        ChangesControllerApplyDiffRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        changeId: z.string(),
    });

    export type Outbound = {
        changeId: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ChangesControllerApplyDiffRequest
    > = z.object({
        changeId: z.string(),
    });
}
