/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EventsControllerTriggerBulkRequest = {
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  bulkTriggerEventDto: components.BulkTriggerEventDto;
};

export type EventsControllerTriggerBulkResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.TriggerEventResponseDto>;
};

/** @internal */
export const EventsControllerTriggerBulkRequest$inboundSchema: z.ZodType<
  EventsControllerTriggerBulkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "idempotency-key": z.string().optional(),
  BulkTriggerEventDto: components.BulkTriggerEventDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "idempotency-key": "idempotencyKey",
    "BulkTriggerEventDto": "bulkTriggerEventDto",
  });
});
/** @internal */
export type EventsControllerTriggerBulkRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  BulkTriggerEventDto: components.BulkTriggerEventDto$Outbound;
};

/** @internal */
export const EventsControllerTriggerBulkRequest$outboundSchema: z.ZodType<
  EventsControllerTriggerBulkRequest$Outbound,
  z.ZodTypeDef,
  EventsControllerTriggerBulkRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  bulkTriggerEventDto: components.BulkTriggerEventDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    bulkTriggerEventDto: "BulkTriggerEventDto",
  });
});

export function eventsControllerTriggerBulkRequestToJSON(
  eventsControllerTriggerBulkRequest: EventsControllerTriggerBulkRequest,
): string {
  return JSON.stringify(
    EventsControllerTriggerBulkRequest$outboundSchema.parse(
      eventsControllerTriggerBulkRequest,
    ),
  );
}
export function eventsControllerTriggerBulkRequestFromJSON(
  jsonString: string,
): SafeParseResult<EventsControllerTriggerBulkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EventsControllerTriggerBulkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsControllerTriggerBulkRequest' from JSON`,
  );
}

/** @internal */
export const EventsControllerTriggerBulkResponse$inboundSchema: z.ZodType<
  EventsControllerTriggerBulkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.array(components.TriggerEventResponseDto$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type EventsControllerTriggerBulkResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Array<components.TriggerEventResponseDto$Outbound>;
};

/** @internal */
export const EventsControllerTriggerBulkResponse$outboundSchema: z.ZodType<
  EventsControllerTriggerBulkResponse$Outbound,
  z.ZodTypeDef,
  EventsControllerTriggerBulkResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.array(components.TriggerEventResponseDto$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function eventsControllerTriggerBulkResponseToJSON(
  eventsControllerTriggerBulkResponse: EventsControllerTriggerBulkResponse,
): string {
  return JSON.stringify(
    EventsControllerTriggerBulkResponse$outboundSchema.parse(
      eventsControllerTriggerBulkResponse,
    ),
  );
}
export function eventsControllerTriggerBulkResponseFromJSON(
  jsonString: string,
): SafeParseResult<EventsControllerTriggerBulkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EventsControllerTriggerBulkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsControllerTriggerBulkResponse' from JSON`,
  );
}
