/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EventsControllerCancelRequest = {
  transactionId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

export type EventsControllerCancelResponse = {
  headers: { [k: string]: Array<string> };
  result: boolean;
};

/** @internal */
export const EventsControllerCancelRequest$inboundSchema: z.ZodType<
  EventsControllerCancelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  transactionId: z.string(),
  "idempotency-key": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "idempotency-key": "idempotencyKey",
  });
});
/** @internal */
export type EventsControllerCancelRequest$Outbound = {
  transactionId: string;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const EventsControllerCancelRequest$outboundSchema: z.ZodType<
  EventsControllerCancelRequest$Outbound,
  z.ZodTypeDef,
  EventsControllerCancelRequest
> = z.object({
  transactionId: z.string(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function eventsControllerCancelRequestToJSON(
  eventsControllerCancelRequest: EventsControllerCancelRequest,
): string {
  return JSON.stringify(
    EventsControllerCancelRequest$outboundSchema.parse(
      eventsControllerCancelRequest,
    ),
  );
}
export function eventsControllerCancelRequestFromJSON(
  jsonString: string,
): SafeParseResult<EventsControllerCancelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsControllerCancelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsControllerCancelRequest' from JSON`,
  );
}

/** @internal */
export const EventsControllerCancelResponse$inboundSchema: z.ZodType<
  EventsControllerCancelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type EventsControllerCancelResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: boolean;
};

/** @internal */
export const EventsControllerCancelResponse$outboundSchema: z.ZodType<
  EventsControllerCancelResponse$Outbound,
  z.ZodTypeDef,
  EventsControllerCancelResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function eventsControllerCancelResponseToJSON(
  eventsControllerCancelResponse: EventsControllerCancelResponse,
): string {
  return JSON.stringify(
    EventsControllerCancelResponse$outboundSchema.parse(
      eventsControllerCancelResponse,
    ),
  );
}
export function eventsControllerCancelResponseFromJSON(
  jsonString: string,
): SafeParseResult<EventsControllerCancelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventsControllerCancelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsControllerCancelResponse' from JSON`,
  );
}
