/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

export type GetActivityStatsSecurity = {
    apiKey?: string | undefined;
    bearer?: string | undefined;
};

/** @internal */
export namespace GetActivityStatsSecurity$ {
    export const inboundSchema: z.ZodType<GetActivityStatsSecurity, z.ZodTypeDef, unknown> = z
        .object({
            "api-key": z.string().optional(),
            bearer: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "api-key": "apiKey",
            });
        });

    export type Outbound = {
        "api-key"?: string | undefined;
        bearer?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetActivityStatsSecurity> = z
        .object({
            apiKey: z.string().optional(),
            bearer: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                apiKey: "api-key",
            });
        });
}
