/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

export type GetChangesSecurity = {
    bearer?: string | undefined;
    apiKey?: string | undefined;
};

export type GetChangesRequest = {
    page?: number | undefined;
    limit?: number | undefined;
    promoted?: string | undefined;
};

/** @internal */
export namespace GetChangesSecurity$ {
    export const inboundSchema: z.ZodType<GetChangesSecurity, z.ZodTypeDef, unknown> = z
        .object({
            bearer: z.string().optional(),
            "api-key": z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "api-key": "apiKey",
            });
        });

    export type Outbound = {
        bearer?: string | undefined;
        "api-key"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChangesSecurity> = z
        .object({
            bearer: z.string().optional(),
            apiKey: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                apiKey: "api-key",
            });
        });
}

/** @internal */
export namespace GetChangesRequest$ {
    export const inboundSchema: z.ZodType<GetChangesRequest, z.ZodTypeDef, unknown> = z.object({
        page: z.number().optional(),
        limit: z.number().default(10),
        promoted: z.string().default("false"),
    });

    export type Outbound = {
        page?: number | undefined;
        limit: number;
        promoted: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetChangesRequest> = z.object({
        page: z.number().optional(),
        limit: z.number().default(10),
        promoted: z.string().default("false"),
    });
}
