/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type LayoutsControllerSetDefaultLayoutRequest = {
    layoutId: string;
};

/** @internal */
export namespace LayoutsControllerSetDefaultLayoutRequest$ {
    export const inboundSchema: z.ZodType<
        LayoutsControllerSetDefaultLayoutRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        layoutId: z.string(),
    });

    export type Outbound = {
        layoutId: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        LayoutsControllerSetDefaultLayoutRequest
    > = z.object({
        layoutId: z.string(),
    });
}
