/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type NotificationGroupsControllerUpdateNotificationGroupRequest = {
    id: string;
    createNotificationGroupRequestDto: components.CreateNotificationGroupRequestDto;
};

/** @internal */
export const NotificationGroupsControllerUpdateNotificationGroupRequest$inboundSchema: z.ZodType<
    NotificationGroupsControllerUpdateNotificationGroupRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        CreateNotificationGroupRequestDto:
            components.CreateNotificationGroupRequestDto$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            CreateNotificationGroupRequestDto: "createNotificationGroupRequestDto",
        });
    });

/** @internal */
export type NotificationGroupsControllerUpdateNotificationGroupRequest$Outbound = {
    id: string;
    CreateNotificationGroupRequestDto: components.CreateNotificationGroupRequestDto$Outbound;
};

/** @internal */
export const NotificationGroupsControllerUpdateNotificationGroupRequest$outboundSchema: z.ZodType<
    NotificationGroupsControllerUpdateNotificationGroupRequest$Outbound,
    z.ZodTypeDef,
    NotificationGroupsControllerUpdateNotificationGroupRequest
> = z
    .object({
        id: z.string(),
        createNotificationGroupRequestDto:
            components.CreateNotificationGroupRequestDto$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            createNotificationGroupRequestDto: "CreateNotificationGroupRequestDto",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationGroupsControllerUpdateNotificationGroupRequest$ {
    /** @deprecated use `NotificationGroupsControllerUpdateNotificationGroupRequest$inboundSchema` instead. */
    export const inboundSchema =
        NotificationGroupsControllerUpdateNotificationGroupRequest$inboundSchema;
    /** @deprecated use `NotificationGroupsControllerUpdateNotificationGroupRequest$outboundSchema` instead. */
    export const outboundSchema =
        NotificationGroupsControllerUpdateNotificationGroupRequest$outboundSchema;
    /** @deprecated use `NotificationGroupsControllerUpdateNotificationGroupRequest$Outbound` instead. */
    export type Outbound = NotificationGroupsControllerUpdateNotificationGroupRequest$Outbound;
}
