/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NotificationGroupsControllerListNotificationGroupsResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.NotificationGroupResponseDto>;
};

/** @internal */
export const NotificationGroupsControllerListNotificationGroupsResponse$inboundSchema:
  z.ZodType<
    NotificationGroupsControllerListNotificationGroupsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: z.array(components.NotificationGroupResponseDto$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type NotificationGroupsControllerListNotificationGroupsResponse$Outbound =
  {
    Headers: { [k: string]: Array<string> };
    Result: Array<components.NotificationGroupResponseDto$Outbound>;
  };

/** @internal */
export const NotificationGroupsControllerListNotificationGroupsResponse$outboundSchema:
  z.ZodType<
    NotificationGroupsControllerListNotificationGroupsResponse$Outbound,
    z.ZodTypeDef,
    NotificationGroupsControllerListNotificationGroupsResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: z.array(components.NotificationGroupResponseDto$outboundSchema),
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NotificationGroupsControllerListNotificationGroupsResponse$ {
  /** @deprecated use `NotificationGroupsControllerListNotificationGroupsResponse$inboundSchema` instead. */
  export const inboundSchema =
    NotificationGroupsControllerListNotificationGroupsResponse$inboundSchema;
  /** @deprecated use `NotificationGroupsControllerListNotificationGroupsResponse$outboundSchema` instead. */
  export const outboundSchema =
    NotificationGroupsControllerListNotificationGroupsResponse$outboundSchema;
  /** @deprecated use `NotificationGroupsControllerListNotificationGroupsResponse$Outbound` instead. */
  export type Outbound =
    NotificationGroupsControllerListNotificationGroupsResponse$Outbound;
}

export function notificationGroupsControllerListNotificationGroupsResponseToJSON(
  notificationGroupsControllerListNotificationGroupsResponse:
    NotificationGroupsControllerListNotificationGroupsResponse,
): string {
  return JSON.stringify(
    NotificationGroupsControllerListNotificationGroupsResponse$outboundSchema
      .parse(notificationGroupsControllerListNotificationGroupsResponse),
  );
}

export function notificationGroupsControllerListNotificationGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  NotificationGroupsControllerListNotificationGroupsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      NotificationGroupsControllerListNotificationGroupsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'NotificationGroupsControllerListNotificationGroupsResponse' from JSON`,
  );
}
