/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type RenameTopicSecurity = {
    bearer?: string | undefined;
    apiKey?: string | undefined;
};

export type RenameTopicRequest = {
    topicKey: string;
    renameTopicRequestDto: components.RenameTopicRequestDto;
};

/** @internal */
export namespace RenameTopicSecurity$ {
    export const inboundSchema: z.ZodType<RenameTopicSecurity, z.ZodTypeDef, unknown> = z
        .object({
            bearer: z.string().optional(),
            "api-key": z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "api-key": "apiKey",
            });
        });

    export type Outbound = {
        bearer?: string | undefined;
        "api-key"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RenameTopicSecurity> = z
        .object({
            bearer: z.string().optional(),
            apiKey: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                apiKey: "api-key",
            });
        });
}

/** @internal */
export namespace RenameTopicRequest$ {
    export const inboundSchema: z.ZodType<RenameTopicRequest, z.ZodTypeDef, unknown> = z
        .object({
            topicKey: z.string(),
            RenameTopicRequestDto: components.RenameTopicRequestDto$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                RenameTopicRequestDto: "renameTopicRequestDto",
            });
        });

    export type Outbound = {
        topicKey: string;
        RenameTopicRequestDto: components.RenameTopicRequestDto$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RenameTopicRequest> = z
        .object({
            topicKey: z.string(),
            renameTopicRequestDto: components.RenameTopicRequestDto$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                renameTopicRequestDto: "RenameTopicRequestDto",
            });
        });
}
