/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscribersControllerRemoveSubscriberRequest = {
  subscriberId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

export type SubscribersControllerRemoveSubscriberResponse = {
  headers: { [k: string]: Array<string> };
  result: components.RemoveSubscriberResponseDto;
};

/** @internal */
export const SubscribersControllerRemoveSubscriberRequest$inboundSchema:
  z.ZodType<
    SubscribersControllerRemoveSubscriberRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    subscriberId: z.string(),
    "idempotency-key": z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "idempotency-key": "idempotencyKey",
    });
  });
/** @internal */
export type SubscribersControllerRemoveSubscriberRequest$Outbound = {
  subscriberId: string;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const SubscribersControllerRemoveSubscriberRequest$outboundSchema:
  z.ZodType<
    SubscribersControllerRemoveSubscriberRequest$Outbound,
    z.ZodTypeDef,
    SubscribersControllerRemoveSubscriberRequest
  > = z.object({
    subscriberId: z.string(),
    idempotencyKey: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  });

export function subscribersControllerRemoveSubscriberRequestToJSON(
  subscribersControllerRemoveSubscriberRequest:
    SubscribersControllerRemoveSubscriberRequest,
): string {
  return JSON.stringify(
    SubscribersControllerRemoveSubscriberRequest$outboundSchema.parse(
      subscribersControllerRemoveSubscriberRequest,
    ),
  );
}
export function subscribersControllerRemoveSubscriberRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribersControllerRemoveSubscriberRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribersControllerRemoveSubscriberRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribersControllerRemoveSubscriberRequest' from JSON`,
  );
}

/** @internal */
export const SubscribersControllerRemoveSubscriberResponse$inboundSchema:
  z.ZodType<
    SubscribersControllerRemoveSubscriberResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.RemoveSubscriberResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });
/** @internal */
export type SubscribersControllerRemoveSubscriberResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.RemoveSubscriberResponseDto$Outbound;
};

/** @internal */
export const SubscribersControllerRemoveSubscriberResponse$outboundSchema:
  z.ZodType<
    SubscribersControllerRemoveSubscriberResponse$Outbound,
    z.ZodTypeDef,
    SubscribersControllerRemoveSubscriberResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: components.RemoveSubscriberResponseDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

export function subscribersControllerRemoveSubscriberResponseToJSON(
  subscribersControllerRemoveSubscriberResponse:
    SubscribersControllerRemoveSubscriberResponse,
): string {
  return JSON.stringify(
    SubscribersControllerRemoveSubscriberResponse$outboundSchema.parse(
      subscribersControllerRemoveSubscriberResponse,
    ),
  );
}
export function subscribersControllerRemoveSubscriberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribersControllerRemoveSubscriberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribersControllerRemoveSubscriberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribersControllerRemoveSubscriberResponse' from JSON`,
  );
}
