/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type SubscribersControllerGetSubscriberPreferenceByLevelRequest = {
    parameter: string;
    subscriberId: string;
};

/** @internal */
export namespace SubscribersControllerGetSubscriberPreferenceByLevelRequest$ {
    export const inboundSchema: z.ZodType<
        SubscribersControllerGetSubscriberPreferenceByLevelRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        parameter: z.string(),
        subscriberId: z.string(),
    });

    export type Outbound = {
        parameter: string;
        subscriberId: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        SubscribersControllerGetSubscriberPreferenceByLevelRequest
    > = z.object({
        parameter: z.string(),
        subscriberId: z.string(),
    });
}
