/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type TopicsControllerRenameTopicRequest = {
    topicKey: string;
    renameTopicRequestDto: components.RenameTopicRequestDto;
};

/** @internal */
export namespace TopicsControllerRenameTopicRequest$ {
    export const inboundSchema: z.ZodType<
        TopicsControllerRenameTopicRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            topicKey: z.string(),
            RenameTopicRequestDto: components.RenameTopicRequestDto$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                RenameTopicRequestDto: "renameTopicRequestDto",
            });
        });

    export type Outbound = {
        topicKey: string;
        RenameTopicRequestDto: components.RenameTopicRequestDto$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        TopicsControllerRenameTopicRequest
    > = z
        .object({
            topicKey: z.string(),
            renameTopicRequestDto: components.RenameTopicRequestDto$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                renameTopicRequestDto: "RenameTopicRequestDto",
            });
        });
}
