/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type UpdateNotificationGroupSecurity = {
    bearer?: string | undefined;
    apiKey?: string | undefined;
};

export type UpdateNotificationGroupRequest = {
    id: string;
    createNotificationGroupRequestDto: components.CreateNotificationGroupRequestDto;
};

/** @internal */
export namespace UpdateNotificationGroupSecurity$ {
    export const inboundSchema: z.ZodType<UpdateNotificationGroupSecurity, z.ZodTypeDef, unknown> =
        z
            .object({
                bearer: z.string().optional(),
                "api-key": z.string().optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    "api-key": "apiKey",
                });
            });

    export type Outbound = {
        bearer?: string | undefined;
        "api-key"?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateNotificationGroupSecurity
    > = z
        .object({
            bearer: z.string().optional(),
            apiKey: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                apiKey: "api-key",
            });
        });
}

/** @internal */
export namespace UpdateNotificationGroupRequest$ {
    export const inboundSchema: z.ZodType<UpdateNotificationGroupRequest, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string(),
            CreateNotificationGroupRequestDto:
                components.CreateNotificationGroupRequestDto$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                CreateNotificationGroupRequestDto: "createNotificationGroupRequestDto",
            });
        });

    export type Outbound = {
        id: string;
        CreateNotificationGroupRequestDto: components.CreateNotificationGroupRequestDto$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateNotificationGroupRequest> =
        z
            .object({
                id: z.string(),
                createNotificationGroupRequestDto:
                    components.CreateNotificationGroupRequestDto$.outboundSchema,
            })
            .transform((v) => {
                return remap$(v, {
                    createNotificationGroupRequestDto: "CreateNotificationGroupRequestDto",
                });
            });
}
