/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type WorkflowControllerChangeActiveStatusRequest = {
    workflowId: string;
    changeWorkflowStatusRequestDto: components.ChangeWorkflowStatusRequestDto;
};

/** @internal */
export namespace WorkflowControllerChangeActiveStatusRequest$ {
    export const inboundSchema: z.ZodType<
        WorkflowControllerChangeActiveStatusRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            workflowId: z.string(),
            ChangeWorkflowStatusRequestDto:
                components.ChangeWorkflowStatusRequestDto$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                ChangeWorkflowStatusRequestDto: "changeWorkflowStatusRequestDto",
            });
        });

    export type Outbound = {
        workflowId: string;
        ChangeWorkflowStatusRequestDto: components.ChangeWorkflowStatusRequestDto$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        WorkflowControllerChangeActiveStatusRequest
    > = z
        .object({
            workflowId: z.string(),
            changeWorkflowStatusRequestDto:
                components.ChangeWorkflowStatusRequestDto$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                changeWorkflowStatusRequestDto: "ChangeWorkflowStatusRequestDto",
            });
        });
}
