/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NotificationStep, NotificationStep$ } from "./notificationstep";
import { PreferenceChannels, PreferenceChannels$ } from "./preferencechannels";
import * as z from "zod";

export type CreateWorkflowRequestDtoNotificationGroup = {};

export type CreateWorkflowRequestDtoData = {};

export type CreateWorkflowRequestDto = {
    name: string;
    notificationGroupId: string;
    notificationGroup?: CreateWorkflowRequestDtoNotificationGroup | undefined;
    tags?: Array<string> | undefined;
    description?: string | undefined;
    steps: Array<NotificationStep>;
    active?: boolean | undefined;
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    draft?: boolean | undefined;
    critical?: boolean | undefined;
    preferenceSettings?: PreferenceChannels | undefined;
    blueprintId?: string | undefined;
    data?: CreateWorkflowRequestDtoData | undefined;
};

/** @internal */
export namespace CreateWorkflowRequestDtoNotificationGroup$ {
    export const inboundSchema: z.ZodType<
        CreateWorkflowRequestDtoNotificationGroup,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateWorkflowRequestDtoNotificationGroup
    > = z.object({});
}

/** @internal */
export namespace CreateWorkflowRequestDtoData$ {
    export const inboundSchema: z.ZodType<CreateWorkflowRequestDtoData, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateWorkflowRequestDtoData> =
        z.object({});
}

/** @internal */
export namespace CreateWorkflowRequestDto$ {
    export const inboundSchema: z.ZodType<CreateWorkflowRequestDto, z.ZodTypeDef, unknown> =
        z.object({
            name: z.string(),
            notificationGroupId: z.string(),
            notificationGroup: z
                .lazy(() => CreateWorkflowRequestDtoNotificationGroup$.inboundSchema)
                .optional(),
            tags: z.array(z.string()).optional(),
            description: z.string().optional(),
            steps: z.array(NotificationStep$.inboundSchema),
            active: z.boolean().optional(),
            draft: z.boolean().optional(),
            critical: z.boolean().optional(),
            preferenceSettings: PreferenceChannels$.inboundSchema.optional(),
            blueprintId: z.string().optional(),
            data: z.lazy(() => CreateWorkflowRequestDtoData$.inboundSchema).optional(),
        });

    export type Outbound = {
        name: string;
        notificationGroupId: string;
        notificationGroup?: CreateWorkflowRequestDtoNotificationGroup$.Outbound | undefined;
        tags?: Array<string> | undefined;
        description?: string | undefined;
        steps: Array<NotificationStep$.Outbound>;
        active?: boolean | undefined;
        draft?: boolean | undefined;
        critical?: boolean | undefined;
        preferenceSettings?: PreferenceChannels$.Outbound | undefined;
        blueprintId?: string | undefined;
        data?: CreateWorkflowRequestDtoData$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateWorkflowRequestDto> =
        z.object({
            name: z.string(),
            notificationGroupId: z.string(),
            notificationGroup: z
                .lazy(() => CreateWorkflowRequestDtoNotificationGroup$.outboundSchema)
                .optional(),
            tags: z.array(z.string()).optional(),
            description: z.string().optional(),
            steps: z.array(NotificationStep$.outboundSchema),
            active: z.boolean().optional(),
            draft: z.boolean().optional(),
            critical: z.boolean().optional(),
            preferenceSettings: PreferenceChannels$.outboundSchema.optional(),
            blueprintId: z.string().optional(),
            data: z.lazy(() => CreateWorkflowRequestDtoData$.outboundSchema).optional(),
        });
}
