/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import { ClosedEnum } from "../../types";
import { CredentialsDto, CredentialsDto$ } from "./credentialsdto";
import { StepFilter, StepFilter$ } from "./stepfilter";
import * as z from "zod";

export const CreateIntegrationRequestDtoChannel = {
    InApp: "in_app",
    Email: "email",
    Sms: "sms",
    Chat: "chat",
    Push: "push",
} as const;
export type CreateIntegrationRequestDtoChannel = ClosedEnum<
    typeof CreateIntegrationRequestDtoChannel
>;

export type CreateIntegrationRequestDto = {
    name?: string | undefined;
    identifier?: string | undefined;
    environmentId?: string | undefined;
    providerId: string;
    channel: CreateIntegrationRequestDtoChannel;
    credentials?: CredentialsDto | undefined;
    /**
     * If the integration is active the validation on the credentials field will run
     */
    active?: boolean | undefined;
    check?: boolean | undefined;
    conditions?: Array<StepFilter> | undefined;
};

/** @internal */
export namespace CreateIntegrationRequestDtoChannel$ {
    export const inboundSchema = z.nativeEnum(CreateIntegrationRequestDtoChannel);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace CreateIntegrationRequestDto$ {
    export const inboundSchema: z.ZodType<CreateIntegrationRequestDto, z.ZodTypeDef, unknown> = z
        .object({
            name: z.string().optional(),
            identifier: z.string().optional(),
            _environmentId: z.string().optional(),
            providerId: z.string(),
            channel: CreateIntegrationRequestDtoChannel$.inboundSchema,
            credentials: CredentialsDto$.inboundSchema.optional(),
            active: z.boolean().optional(),
            check: z.boolean().optional(),
            conditions: z.array(StepFilter$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                _environmentId: "environmentId",
            });
        });

    export type Outbound = {
        name?: string | undefined;
        identifier?: string | undefined;
        _environmentId?: string | undefined;
        providerId: string;
        channel: string;
        credentials?: CredentialsDto$.Outbound | undefined;
        active?: boolean | undefined;
        check?: boolean | undefined;
        conditions?: Array<StepFilter$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateIntegrationRequestDto> = z
        .object({
            name: z.string().optional(),
            identifier: z.string().optional(),
            environmentId: z.string().optional(),
            providerId: z.string(),
            channel: CreateIntegrationRequestDtoChannel$.outboundSchema,
            credentials: CredentialsDto$.outboundSchema.optional(),
            active: z.boolean().optional(),
            check: z.boolean().optional(),
            conditions: z.array(StepFilter$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                environmentId: "_environmentId",
            });
        });
}
