/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateUpdateTopicRequestDto = {
  /**
   * The unique key identifier for the topic. The key must contain only alphanumeric characters (a-z, A-Z, 0-9), hyphens (-), underscores (_), colons (:), or be a valid email address.
   */
  key: string;
  /**
   * The display name for the topic
   */
  name?: string | undefined;
};

/** @internal */
export const CreateUpdateTopicRequestDto$inboundSchema: z.ZodType<
  CreateUpdateTopicRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  name: z.string().optional(),
});
/** @internal */
export type CreateUpdateTopicRequestDto$Outbound = {
  key: string;
  name?: string | undefined;
};

/** @internal */
export const CreateUpdateTopicRequestDto$outboundSchema: z.ZodType<
  CreateUpdateTopicRequestDto$Outbound,
  z.ZodTypeDef,
  CreateUpdateTopicRequestDto
> = z.object({
  key: z.string(),
  name: z.string().optional(),
});

export function createUpdateTopicRequestDtoToJSON(
  createUpdateTopicRequestDto: CreateUpdateTopicRequestDto,
): string {
  return JSON.stringify(
    CreateUpdateTopicRequestDto$outboundSchema.parse(
      createUpdateTopicRequestDto,
    ),
  );
}
export function createUpdateTopicRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<CreateUpdateTopicRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUpdateTopicRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUpdateTopicRequestDto' from JSON`,
  );
}
