/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type CreateTenantResponseDtoData = {};

export type CreateTenantResponseDto = {
    environmentId: string;
    id: string;
    createdAt: string;
    data?: CreateTenantResponseDtoData | undefined;
    identifier: string;
    name?: string | undefined;
    updatedAt: string;
};

/** @internal */
export namespace CreateTenantResponseDtoData$ {
    export const inboundSchema: z.ZodType<CreateTenantResponseDtoData, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateTenantResponseDtoData> =
        z.object({});
}

/** @internal */
export namespace CreateTenantResponseDto$ {
    export const inboundSchema: z.ZodType<CreateTenantResponseDto, z.ZodTypeDef, unknown> = z
        .object({
            _environmentId: z.string(),
            _id: z.string(),
            createdAt: z.string(),
            data: z.lazy(() => CreateTenantResponseDtoData$.inboundSchema).optional(),
            identifier: z.string(),
            name: z.string().optional(),
            updatedAt: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                _environmentId: "environmentId",
                _id: "id",
            });
        });

    export type Outbound = {
        _environmentId: string;
        _id: string;
        createdAt: string;
        data?: CreateTenantResponseDtoData$.Outbound | undefined;
        identifier: string;
        name?: string | undefined;
        updatedAt: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateTenantResponseDto> = z
        .object({
            environmentId: z.string(),
            id: z.string(),
            createdAt: z.string(),
            data: z.lazy(() => CreateTenantResponseDtoData$.outboundSchema).optional(),
            identifier: z.string(),
            name: z.string().optional(),
            updatedAt: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                environmentId: "_environmentId",
                id: "_id",
            });
        });
}
