/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateNotificationGroupRequestDto = {
  name: string;
};

/** @internal */
export const CreateNotificationGroupRequestDto$inboundSchema: z.ZodType<
  CreateNotificationGroupRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type CreateNotificationGroupRequestDto$Outbound = {
  name: string;
};

/** @internal */
export const CreateNotificationGroupRequestDto$outboundSchema: z.ZodType<
  CreateNotificationGroupRequestDto$Outbound,
  z.ZodTypeDef,
  CreateNotificationGroupRequestDto
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateNotificationGroupRequestDto$ {
  /** @deprecated use `CreateNotificationGroupRequestDto$inboundSchema` instead. */
  export const inboundSchema = CreateNotificationGroupRequestDto$inboundSchema;
  /** @deprecated use `CreateNotificationGroupRequestDto$outboundSchema` instead. */
  export const outboundSchema =
    CreateNotificationGroupRequestDto$outboundSchema;
  /** @deprecated use `CreateNotificationGroupRequestDto$Outbound` instead. */
  export type Outbound = CreateNotificationGroupRequestDto$Outbound;
}
