/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomControlDto,
  CustomControlDto$inboundSchema,
  CustomControlDto$Outbound,
  CustomControlDto$outboundSchema,
} from "./customcontroldto.js";
import {
  UiSchema,
  UiSchema$inboundSchema,
  UiSchema$Outbound,
  UiSchema$outboundSchema,
} from "./uischema.js";

export type CustomControlsMetadataResponseDto = {
  /**
   * JSON Schema for data
   */
  dataSchema?: { [k: string]: any } | undefined;
  /**
   * UI Schema for rendering
   */
  uiSchema?: UiSchema | undefined;
  /**
   * Control values specific to Custom step
   */
  values: CustomControlDto;
};

/** @internal */
export const CustomControlsMetadataResponseDto$inboundSchema: z.ZodType<
  CustomControlsMetadataResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  dataSchema: z.record(z.any()).optional(),
  uiSchema: UiSchema$inboundSchema.optional(),
  values: CustomControlDto$inboundSchema,
});
/** @internal */
export type CustomControlsMetadataResponseDto$Outbound = {
  dataSchema?: { [k: string]: any } | undefined;
  uiSchema?: UiSchema$Outbound | undefined;
  values: CustomControlDto$Outbound;
};

/** @internal */
export const CustomControlsMetadataResponseDto$outboundSchema: z.ZodType<
  CustomControlsMetadataResponseDto$Outbound,
  z.ZodTypeDef,
  CustomControlsMetadataResponseDto
> = z.object({
  dataSchema: z.record(z.any()).optional(),
  uiSchema: UiSchema$outboundSchema.optional(),
  values: CustomControlDto$outboundSchema,
});

export function customControlsMetadataResponseDtoToJSON(
  customControlsMetadataResponseDto: CustomControlsMetadataResponseDto,
): string {
  return JSON.stringify(
    CustomControlsMetadataResponseDto$outboundSchema.parse(
      customControlsMetadataResponseDto,
    ),
  );
}
export function customControlsMetadataResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<CustomControlsMetadataResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomControlsMetadataResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomControlsMetadataResponseDto' from JSON`,
  );
}
