/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const HumanSignalDtoType = {
  Human: "human",
} as const;
export type HumanSignalDtoType = ClosedEnum<typeof HumanSignalDtoType>;

/**
 * Interaction verb queued by `ctx.ask` / `ctx.approve` / `ctx.choose` / `ctx.tell`.
 */
export const Kind = {
  Ask: "ask",
  Approve: "approve",
  Choose: "choose",
  Tell: "tell",
} as const;
/**
 * Interaction verb queued by `ctx.ask` / `ctx.approve` / `ctx.choose` / `ctx.tell`.
 */
export type Kind = ClosedEnum<typeof Kind>;

/**
 * Novu subscriberId(s) allowed to settle this interaction (max 50). First valid answer wins. When omitted, the conversation subscriber is used. Subscriber ids only — not workflow topic recipients.
 */
export type HumanSignalDtoTo = string | Array<string>;

export type HumanSignalDto = {
  type: HumanSignalDtoType;
  /**
   * Interaction verb queued by `ctx.ask` / `ctx.approve` / `ctx.choose` / `ctx.tell`.
   */
  kind: Kind;
  /**
   * Question, action description, or one-way message shown to the human.
   */
  prompt: string;
  /**
   * Client-minted id returned by the framework helper; echoed on `ctx.humanResponse.requestId`.
   */
  requestId: string;
  /**
   * Choice labels — required for `choose`, ignored otherwise.
   */
  options?: Array<string> | undefined;
  /**
   * Attribution label rendered in the card.
   */
  from?: string | undefined;
  /**
   * Seconds until the interaction expires. Default 86400 (24h), max 259200.
   */
  ttlSeconds?: number | undefined;
  /**
   * Novu subscriberId(s) allowed to settle this interaction (max 50). First valid answer wins. When omitted, the conversation subscriber is used. Subscriber ids only — not workflow topic recipients.
   */
  to?: string | Array<string> | undefined;
};

/** @internal */
export const HumanSignalDtoType$outboundSchema: z.ZodNativeEnum<
  typeof HumanSignalDtoType
> = z.nativeEnum(HumanSignalDtoType);

/** @internal */
export const Kind$outboundSchema: z.ZodNativeEnum<typeof Kind> = z.nativeEnum(
  Kind,
);

/** @internal */
export type HumanSignalDtoTo$Outbound = string | Array<string>;

/** @internal */
export const HumanSignalDtoTo$outboundSchema: z.ZodType<
  HumanSignalDtoTo$Outbound,
  z.ZodTypeDef,
  HumanSignalDtoTo
> = z.union([z.string(), z.array(z.string())]);

export function humanSignalDtoToToJSON(
  humanSignalDtoTo: HumanSignalDtoTo,
): string {
  return JSON.stringify(
    HumanSignalDtoTo$outboundSchema.parse(humanSignalDtoTo),
  );
}

/** @internal */
export type HumanSignalDto$Outbound = {
  type: string;
  kind: string;
  prompt: string;
  requestId: string;
  options?: Array<string> | undefined;
  from?: string | undefined;
  ttlSeconds?: number | undefined;
  to?: string | Array<string> | undefined;
};

/** @internal */
export const HumanSignalDto$outboundSchema: z.ZodType<
  HumanSignalDto$Outbound,
  z.ZodTypeDef,
  HumanSignalDto
> = z.object({
  type: HumanSignalDtoType$outboundSchema,
  kind: Kind$outboundSchema,
  prompt: z.string(),
  requestId: z.string(),
  options: z.array(z.string()).optional(),
  from: z.string().optional(),
  ttlSeconds: z.number().optional(),
  to: z.union([z.string(), z.array(z.string())]).optional(),
});

export function humanSignalDtoToJSON(humanSignalDto: HumanSignalDto): string {
  return JSON.stringify(HumanSignalDto$outboundSchema.parse(humanSignalDto));
}
