/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type MemberUserDto = {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
};

/** @internal */
export namespace MemberUserDto$ {
    export const inboundSchema: z.ZodType<MemberUserDto, z.ZodTypeDef, unknown> = z
        .object({
            _id: z.string(),
            email: z.string(),
            firstName: z.string(),
            lastName: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                _id: "id",
            });
        });

    export type Outbound = {
        _id: string;
        email: string;
        firstName: string;
        lastName: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, MemberUserDto> = z
        .object({
            id: z.string(),
            email: z.string(),
            firstName: z.string(),
            lastName: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                id: "_id",
            });
        });
}
