/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ButtonTypeEnum,
  ButtonTypeEnum$inboundSchema,
  ButtonTypeEnum$outboundSchema,
} from "./buttontypeenum.js";

/**
 * Payload of the action result
 */
export type Payload = {};

export type MessageActionResult = {
  /**
   * Payload of the action result
   */
  payload?: Payload | undefined;
  /**
   * Type of button for the action result
   */
  type?: ButtonTypeEnum | undefined;
};

/** @internal */
export const Payload$inboundSchema: z.ZodType<Payload, z.ZodTypeDef, unknown> =
  z.object({});
/** @internal */
export type Payload$Outbound = {};

/** @internal */
export const Payload$outboundSchema: z.ZodType<
  Payload$Outbound,
  z.ZodTypeDef,
  Payload
> = z.object({});

export function payloadToJSON(payload: Payload): string {
  return JSON.stringify(Payload$outboundSchema.parse(payload));
}
export function payloadFromJSON(
  jsonString: string,
): SafeParseResult<Payload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payload' from JSON`,
  );
}

/** @internal */
export const MessageActionResult$inboundSchema: z.ZodType<
  MessageActionResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  payload: z.lazy(() => Payload$inboundSchema).optional(),
  type: ButtonTypeEnum$inboundSchema.optional(),
});
/** @internal */
export type MessageActionResult$Outbound = {
  payload?: Payload$Outbound | undefined;
  type?: string | undefined;
};

/** @internal */
export const MessageActionResult$outboundSchema: z.ZodType<
  MessageActionResult$Outbound,
  z.ZodTypeDef,
  MessageActionResult
> = z.object({
  payload: z.lazy(() => Payload$outboundSchema).optional(),
  type: ButtonTypeEnum$outboundSchema.optional(),
});

export function messageActionResultToJSON(
  messageActionResult: MessageActionResult,
): string {
  return JSON.stringify(
    MessageActionResult$outboundSchema.parse(messageActionResult),
  );
}
export function messageActionResultFromJSON(
  jsonString: string,
): SafeParseResult<MessageActionResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageActionResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageActionResult' from JSON`,
  );
}
