/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MessageTemplate = {};

/** @internal */
export const MessageTemplate$inboundSchema: z.ZodType<
  MessageTemplate,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type MessageTemplate$Outbound = {};

/** @internal */
export const MessageTemplate$outboundSchema: z.ZodType<
  MessageTemplate$Outbound,
  z.ZodTypeDef,
  MessageTemplate
> = z.object({});

export function messageTemplateToJSON(
  messageTemplate: MessageTemplate,
): string {
  return JSON.stringify(MessageTemplate$outboundSchema.parse(messageTemplate));
}
export function messageTemplateFromJSON(
  jsonString: string,
): SafeParseResult<MessageTemplate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageTemplate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageTemplate' from JSON`,
  );
}
