/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { DelayRegularMetadata, DelayRegularMetadata$ } from "./delayregularmetadata.js";
import { DelayScheduledMetadata, DelayScheduledMetadata$ } from "./delayscheduledmetadata.js";
import { DigestRegularMetadata, DigestRegularMetadata$ } from "./digestregularmetadata.js";
import { DigestTimedMetadata, DigestTimedMetadata$ } from "./digesttimedmetadata.js";
import { MessageTemplate, MessageTemplate$ } from "./messagetemplate.js";
import { StepFilter, StepFilter$ } from "./stepfilter.js";
import * as z from "zod";

export type NotificationStepVariantParentId = {};

export type NotificationStepVariantMetadata =
    | DelayScheduledMetadata
    | DelayRegularMetadata
    | DigestTimedMetadata
    | DigestRegularMetadata;

export type NotificationStepVariantReplyCallback = {};

export type NotificationStepVariant = {
    id?: string | undefined;
    parentId?: NotificationStepVariantParentId | undefined;
    templateId?: string | undefined;
    active?: boolean | undefined;
    filters?: Array<StepFilter> | undefined;
    metadata?:
        | DelayScheduledMetadata
        | DelayRegularMetadata
        | DigestTimedMetadata
        | DigestRegularMetadata
        | undefined;
    name?: string | undefined;
    replyCallback?: NotificationStepVariantReplyCallback | undefined;
    shouldStopOnFail?: boolean | undefined;
    template?: MessageTemplate | undefined;
    uuid?: string | undefined;
};

/** @internal */
export namespace NotificationStepVariantParentId$ {
    export const inboundSchema: z.ZodType<NotificationStepVariantParentId, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        NotificationStepVariantParentId
    > = z.object({});
}

/** @internal */
export namespace NotificationStepVariantMetadata$ {
    export const inboundSchema: z.ZodType<NotificationStepVariantMetadata, z.ZodTypeDef, unknown> =
        z.union([
            DelayScheduledMetadata$.inboundSchema,
            DelayRegularMetadata$.inboundSchema,
            DigestTimedMetadata$.inboundSchema,
            DigestRegularMetadata$.inboundSchema,
        ]);

    export type Outbound =
        | DelayScheduledMetadata$.Outbound
        | DelayRegularMetadata$.Outbound
        | DigestTimedMetadata$.Outbound
        | DigestRegularMetadata$.Outbound;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        NotificationStepVariantMetadata
    > = z.union([
        DelayScheduledMetadata$.outboundSchema,
        DelayRegularMetadata$.outboundSchema,
        DigestTimedMetadata$.outboundSchema,
        DigestRegularMetadata$.outboundSchema,
    ]);
}

/** @internal */
export namespace NotificationStepVariantReplyCallback$ {
    export const inboundSchema: z.ZodType<
        NotificationStepVariantReplyCallback,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        NotificationStepVariantReplyCallback
    > = z.object({});
}

/** @internal */
export namespace NotificationStepVariant$ {
    export const inboundSchema: z.ZodType<NotificationStepVariant, z.ZodTypeDef, unknown> = z
        .object({
            _id: z.string().optional(),
            _parentId: z.lazy(() => NotificationStepVariantParentId$.inboundSchema).optional(),
            _templateId: z.string().optional(),
            active: z.boolean().optional(),
            filters: z.array(StepFilter$.inboundSchema).optional(),
            metadata: z
                .union([
                    DelayScheduledMetadata$.inboundSchema,
                    DelayRegularMetadata$.inboundSchema,
                    DigestTimedMetadata$.inboundSchema,
                    DigestRegularMetadata$.inboundSchema,
                ])
                .optional(),
            name: z.string().optional(),
            replyCallback: z
                .lazy(() => NotificationStepVariantReplyCallback$.inboundSchema)
                .optional(),
            shouldStopOnFail: z.boolean().optional(),
            template: MessageTemplate$.inboundSchema.optional(),
            uuid: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                _id: "id",
                _parentId: "parentId",
                _templateId: "templateId",
            });
        });

    export type Outbound = {
        _id?: string | undefined;
        _parentId?: NotificationStepVariantParentId$.Outbound | undefined;
        _templateId?: string | undefined;
        active?: boolean | undefined;
        filters?: Array<StepFilter$.Outbound> | undefined;
        metadata?:
            | DelayScheduledMetadata$.Outbound
            | DelayRegularMetadata$.Outbound
            | DigestTimedMetadata$.Outbound
            | DigestRegularMetadata$.Outbound
            | undefined;
        name?: string | undefined;
        replyCallback?: NotificationStepVariantReplyCallback$.Outbound | undefined;
        shouldStopOnFail?: boolean | undefined;
        template?: MessageTemplate$.Outbound | undefined;
        uuid?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, NotificationStepVariant> = z
        .object({
            id: z.string().optional(),
            parentId: z.lazy(() => NotificationStepVariantParentId$.outboundSchema).optional(),
            templateId: z.string().optional(),
            active: z.boolean().optional(),
            filters: z.array(StepFilter$.outboundSchema).optional(),
            metadata: z
                .union([
                    DelayScheduledMetadata$.outboundSchema,
                    DelayRegularMetadata$.outboundSchema,
                    DigestTimedMetadata$.outboundSchema,
                    DigestRegularMetadata$.outboundSchema,
                ])
                .optional(),
            name: z.string().optional(),
            replyCallback: z
                .lazy(() => NotificationStepVariantReplyCallback$.outboundSchema)
                .optional(),
            shouldStopOnFail: z.boolean().optional(),
            template: MessageTemplate$.outboundSchema.optional(),
            uuid: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                id: "_id",
                parentId: "_parentId",
                templateId: "_templateId",
            });
        });
}
