/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    IPartnerConfigurationResponseDto,
    IPartnerConfigurationResponseDto$,
} from "./ipartnerconfigurationresponsedto.js";
import {
    OrganizationBrandingResponseDto,
    OrganizationBrandingResponseDto$,
} from "./organizationbrandingresponsedto.js";
import * as z from "zod";

export type OrganizationResponseDto = {
    branding: OrganizationBrandingResponseDto;
    logo?: string | undefined;
    name: string;
    partnerConfigurations?: Array<IPartnerConfigurationResponseDto> | undefined;
};

/** @internal */
export namespace OrganizationResponseDto$ {
    export const inboundSchema: z.ZodType<OrganizationResponseDto, z.ZodTypeDef, unknown> =
        z.object({
            branding: OrganizationBrandingResponseDto$.inboundSchema,
            logo: z.string().optional(),
            name: z.string(),
            partnerConfigurations: z
                .array(IPartnerConfigurationResponseDto$.inboundSchema)
                .optional(),
        });

    export type Outbound = {
        branding: OrganizationBrandingResponseDto$.Outbound;
        logo?: string | undefined;
        name: string;
        partnerConfigurations?: Array<IPartnerConfigurationResponseDto$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, OrganizationResponseDto> =
        z.object({
            branding: OrganizationBrandingResponseDto$.outboundSchema,
            logo: z.string().optional(),
            name: z.string(),
            partnerConfigurations: z
                .array(IPartnerConfigurationResponseDto$.outboundSchema)
                .optional(),
        });
}
