/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const TopicPayloadDtoType = {
  Subscriber: "Subscriber",
  Topic: "Topic",
} as const;
export type TopicPayloadDtoType = ClosedEnum<typeof TopicPayloadDtoType>;

export type TopicPayloadDto = {
  topicKey: string;
  type: TopicPayloadDtoType;
};

/** @internal */
export const TopicPayloadDtoType$inboundSchema: z.ZodNativeEnum<
  typeof TopicPayloadDtoType
> = z.nativeEnum(TopicPayloadDtoType);

/** @internal */
export const TopicPayloadDtoType$outboundSchema: z.ZodNativeEnum<
  typeof TopicPayloadDtoType
> = TopicPayloadDtoType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicPayloadDtoType$ {
  /** @deprecated use `TopicPayloadDtoType$inboundSchema` instead. */
  export const inboundSchema = TopicPayloadDtoType$inboundSchema;
  /** @deprecated use `TopicPayloadDtoType$outboundSchema` instead. */
  export const outboundSchema = TopicPayloadDtoType$outboundSchema;
}

/** @internal */
export const TopicPayloadDto$inboundSchema: z.ZodType<
  TopicPayloadDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  topicKey: z.string(),
  type: TopicPayloadDtoType$inboundSchema,
});

/** @internal */
export type TopicPayloadDto$Outbound = {
  topicKey: string;
  type: string;
};

/** @internal */
export const TopicPayloadDto$outboundSchema: z.ZodType<
  TopicPayloadDto$Outbound,
  z.ZodTypeDef,
  TopicPayloadDto
> = z.object({
  topicKey: z.string(),
  type: TopicPayloadDtoType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TopicPayloadDto$ {
  /** @deprecated use `TopicPayloadDto$inboundSchema` instead. */
  export const inboundSchema = TopicPayloadDto$inboundSchema;
  /** @deprecated use `TopicPayloadDto$outboundSchema` instead. */
  export const outboundSchema = TopicPayloadDto$outboundSchema;
  /** @deprecated use `TopicPayloadDto$Outbound` instead. */
  export type Outbound = TopicPayloadDto$Outbound;
}
