/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateSubscriberRequestDtoData = {};

export type UpdateSubscriberRequestDto = {
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    phone?: string | undefined;
    avatar?: string | undefined;
    locale?: string | undefined;
    data?: UpdateSubscriberRequestDtoData | undefined;
};

/** @internal */
export namespace UpdateSubscriberRequestDtoData$ {
    export const inboundSchema: z.ZodType<UpdateSubscriberRequestDtoData, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateSubscriberRequestDtoData> =
        z.object({});
}

/** @internal */
export namespace UpdateSubscriberRequestDto$ {
    export const inboundSchema: z.ZodType<UpdateSubscriberRequestDto, z.ZodTypeDef, unknown> =
        z.object({
            email: z.string().optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            phone: z.string().optional(),
            avatar: z.string().optional(),
            locale: z.string().optional(),
            data: z.lazy(() => UpdateSubscriberRequestDtoData$.inboundSchema).optional(),
        });

    export type Outbound = {
        email?: string | undefined;
        firstName?: string | undefined;
        lastName?: string | undefined;
        phone?: string | undefined;
        avatar?: string | undefined;
        locale?: string | undefined;
        data?: UpdateSubscriberRequestDtoData$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateSubscriberRequestDto> =
        z.object({
            email: z.string().optional(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            phone: z.string().optional(),
            avatar: z.string().optional(),
            locale: z.string().optional(),
            data: z.lazy(() => UpdateSubscriberRequestDtoData$.outboundSchema).optional(),
        });
}
