/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateTenantRequestDtoData = {};

export type UpdateTenantRequestDto = {
    identifier?: string | undefined;
    name?: string | undefined;
    data?: UpdateTenantRequestDtoData | undefined;
};

/** @internal */
export namespace UpdateTenantRequestDtoData$ {
    export const inboundSchema: z.ZodType<UpdateTenantRequestDtoData, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateTenantRequestDtoData> =
        z.object({});
}

/** @internal */
export namespace UpdateTenantRequestDto$ {
    export const inboundSchema: z.ZodType<UpdateTenantRequestDto, z.ZodTypeDef, unknown> = z.object(
        {
            identifier: z.string().optional(),
            name: z.string().optional(),
            data: z.lazy(() => UpdateTenantRequestDtoData$.inboundSchema).optional(),
        }
    );

    export type Outbound = {
        identifier?: string | undefined;
        name?: string | undefined;
        data?: UpdateTenantRequestDtoData$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateTenantRequestDto> =
        z.object({
            identifier: z.string().optional(),
            name: z.string().optional(),
            data: z.lazy(() => UpdateTenantRequestDtoData$.outboundSchema).optional(),
        });
}
