/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateBrandingDetailsDto = {
    color: string;
    contentBackground: string;
    fontColor: string;
    fontFamily?: string | undefined;
    logo: string;
};

/** @internal */
export namespace UpdateBrandingDetailsDto$ {
    export const inboundSchema: z.ZodType<UpdateBrandingDetailsDto, z.ZodTypeDef, unknown> =
        z.object({
            color: z.string(),
            contentBackground: z.string(),
            fontColor: z.string(),
            fontFamily: z.string().optional(),
            logo: z.string(),
        });

    export type Outbound = {
        color: string;
        contentBackground: string;
        fontColor: string;
        fontFamily?: string | undefined;
        logo: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateBrandingDetailsDto> =
        z.object({
            color: z.string(),
            contentBackground: z.string(),
            fontColor: z.string(),
            fontFamily: z.string().optional(),
            logo: z.string(),
        });
}
