/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import { ClosedEnum } from "../../types";
import * as z from "zod";

export const UpdateLayoutResponseDtoChannel = {
    InApp: "in_app",
    Email: "email",
    Sms: "sms",
    Chat: "chat",
    Push: "push",
} as const;
export type UpdateLayoutResponseDtoChannel = ClosedEnum<typeof UpdateLayoutResponseDtoChannel>;

export type UpdateLayoutResponseDtoVariables = {};

export type UpdateLayoutResponseDto = {
    id?: string | undefined;
    organizationId: string;
    environmentId: string;
    creatorId: string;
    name: string;
    identifier: string;
    description?: string | undefined;
    channel: UpdateLayoutResponseDtoChannel;
    content: string;
    contentType: string;
    variables?: Array<UpdateLayoutResponseDtoVariables> | undefined;
    isDefault: boolean;
    isDeleted: boolean;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
    parentId?: string | undefined;
};

/** @internal */
export namespace UpdateLayoutResponseDtoChannel$ {
    export const inboundSchema = z.nativeEnum(UpdateLayoutResponseDtoChannel);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace UpdateLayoutResponseDtoVariables$ {
    export const inboundSchema: z.ZodType<UpdateLayoutResponseDtoVariables, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateLayoutResponseDtoVariables
    > = z.object({});
}

/** @internal */
export namespace UpdateLayoutResponseDto$ {
    export const inboundSchema: z.ZodType<UpdateLayoutResponseDto, z.ZodTypeDef, unknown> = z
        .object({
            _id: z.string().optional(),
            _organizationId: z.string(),
            _environmentId: z.string(),
            _creatorId: z.string(),
            name: z.string(),
            identifier: z.string(),
            description: z.string().optional(),
            channel: UpdateLayoutResponseDtoChannel$.inboundSchema,
            content: z.string(),
            contentType: z.string(),
            variables: z
                .array(z.lazy(() => UpdateLayoutResponseDtoVariables$.inboundSchema))
                .optional(),
            isDefault: z.boolean(),
            isDeleted: z.boolean(),
            createdAt: z.string().optional(),
            updatedAt: z.string().optional(),
            _parentId: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                _id: "id",
                _organizationId: "organizationId",
                _environmentId: "environmentId",
                _creatorId: "creatorId",
                _parentId: "parentId",
            });
        });

    export type Outbound = {
        _id?: string | undefined;
        _organizationId: string;
        _environmentId: string;
        _creatorId: string;
        name: string;
        identifier: string;
        description?: string | undefined;
        channel: string;
        content: string;
        contentType: string;
        variables?: Array<UpdateLayoutResponseDtoVariables$.Outbound> | undefined;
        isDefault: boolean;
        isDeleted: boolean;
        createdAt?: string | undefined;
        updatedAt?: string | undefined;
        _parentId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateLayoutResponseDto> = z
        .object({
            id: z.string().optional(),
            organizationId: z.string(),
            environmentId: z.string(),
            creatorId: z.string(),
            name: z.string(),
            identifier: z.string(),
            description: z.string().optional(),
            channel: UpdateLayoutResponseDtoChannel$.outboundSchema,
            content: z.string(),
            contentType: z.string(),
            variables: z
                .array(z.lazy(() => UpdateLayoutResponseDtoVariables$.outboundSchema))
                .optional(),
            isDefault: z.boolean(),
            isDeleted: z.boolean(),
            createdAt: z.string().optional(),
            updatedAt: z.string().optional(),
            parentId: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                id: "_id",
                organizationId: "_organizationId",
                environmentId: "_environmentId",
                creatorId: "_creatorId",
                parentId: "_parentId",
            });
        });
}
